appearance: {}
feature: {}
folder:
  uploads: /usr/share/models
gcodeViewer: {}
plugins:
  cura:
    _config_version: null
    cura_engine: /usr/bin/CuraEngine
    debug_logging: false
    default_profile: null
printerParameters: {}
serial:
  additionalPorts:
  - /dev/octoprint_1
  baudrate: 115200
  port: /dev/octoprint_1
  timeout: {}
system: {}
temperature: {}
webcam: {}
controls:
  - name: Stepper current and microstepping
    layout: vertical
    children:
    - name: Set
      layout: vertical
      commands: 
       - M906 X%(current_x)s
       - M909 X%(microstepping_x)s
      input:
      - default: 500
        name: Current X
        parameter: current_x
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping X
        parameter: microstepping_x
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands: 
       - M906 Y%(current_y)s
       - M909 Y%(microstepping_y)s
      input:
      - default: 500
        name: Current Y
        parameter: current_y
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping Y
        parameter: microstepping_y
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands: 
       - M906 Z%(current_z)s
       - M909 Z%(microstepping_z)s
      input:
      - default: 500
        name: Current Z
        parameter: current_z
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping Z
        parameter: microstepping_z
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands: 
       - M906 E%(current_e)s
       - M909 E%(microstepping_e)s
      input:
      - default: 500
        name: Current E
        parameter: current_e
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping E
        parameter: microstepping_e
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands: 
       - M906 H%(current_h)s
       - M909 H%(microstepping_h)s
      input:
      - default: 500
        name: Current H
        parameter: current_h
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping H
        parameter: microstepping_h
        slider:
          max: 7
          min: 0
          step: 1
  - name: Stepper steps pr mm and direction
    layout: vertical
    children:
    - name: Set
      layout: vertical
      commands: 
       - M569 X%(direction_x)s
       - M92  X%(steps_pr_mm_x)s
      input:
      - default: 10
        name: Steps pr mm X
        parameter: steps_pr_mm_x
      - default: 0
        name: Invert X
        parameter: direction_x
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands: 
       - M569 Y%(direction_y)s
       - M92  Y%(steps_pr_mm_y)s
      input:
      - default: 10
        name: Steps pr mm Y
        parameter: steps_pr_mm_y
      - default: 0
        name: Invert Y
        parameter: direction_y
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands: 
       - M569 Z%(direction_z)s
       - M92  Z%(steps_pr_mm_z)s
      input:
      - default: 10
        name: Steps pr mm Z
        parameter: steps_pr_mm_z
      - default: 0
        name: Invert Z
        parameter: direction_z
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands: 
       - M569 E%(direction_e)s
       - M92  E%(steps_pr_mm_e)s
      input:
      - default: 10
        name: Steps pr mm E
        parameter: steps_pr_mm_e
      - default: 0
        name: Invert E
        parameter: direction_e
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands: 
       - M569 H%(direction_h)s
       - M92  H%(steps_pr_mm_h)s
      input:
      - default: 10
        name: Steps pr mm H
        parameter: steps_pr_mm_h
      - default: 0
        name: Invert H
        parameter: direction_h
        slider:
          max: 1
          min: -1
          step: 2
  - name: PID
    layout: horizontal
    children:
      - name: Set PID E
        commands:
          - M130 P0 S%(pid_p_e)s
          - M131 P0 S%(pid_i_e)s
          - M132 P0 S%(pid_d_e)s
        input:
          - name: P
            parameter: pid_p_e
          - name: I
            parameter: pid_i_e
          - name: D
            parameter: pid_d_e
      - name: Set PID H
        commands:
          - M130 P1 S%(pid_p_h)s
          - M131 P1 S%(pid_i_h)s
          - M132 P1 S%(pid_d_h)s
        input:
          - name: P
            parameter: pid_p_h
          - name: I
            parameter: pid_i_h
          - name: D
            parameter: pid_d_h
      - name: Set PID Bed
        commands:
          - M130 P2 S%(pid_p_hbp)s
          - M131 P2 S%(pid_i_hbp)s
          - M132 P2 S%(pid_d_hbp)s
        input:
          - name: P
            parameter: pid_p_hbp
          - name: I
            parameter: pid_i_hbp
          - name: D
            parameter: pid_d_hbp

