appearance:
  name: Kamikaze 2.1.1
feature: {}
folder:
  uploads: /usr/share/models
gcodeViewer: {}
plugins:
  cura:
    _config_version: null
    cura_engine: /usr/bin/CuraEngine
    debug_logging: false
    default_profile: null
  softwareupdate:
    _config_version: 4
    checks:
      Redeem:
        checkout_folder: /usr/src/redeem
        type: git_commit
        update_script: '{python} "/usr/src/redeem/update-redeem.py" --python="{python}" --sudo "{folder}" "{target}"'
        restart: 'echo "Redeem dummy restart"'
      Toggle:
        checkout_folder: /usr/src/toggle
        type: git_commit
        update_script: '{python} "/usr/src/toggle/update-toggle.py" --python="{python}" "{folder}" "{target}"'
        restart: 'echo "Toggle dummy restart"'
      octoprint:
        checkout_folder: /home/octo/OctoPrint
        prerelease: false
        type: github_release
      Kamikaze:
        checkout_folder: /usr/src/Kamikaze2
        type: git_commit
        update_script: '/usr/src/Kamikaze2/update-kamikaze.sh'
        restart: 'echo "Kamikaze dummy restart"'
printerParameters: {}
serial:
  additionalPorts:
  - /dev/octoprint_1
  baudrate: 115200
  port: /dev/octoprint_1
  timeout: {}
server:
  commands:
    serverRestartCommand: sudo systemctl restart octoprint.service
    systemRestartCommand: sudo reboot
    systemShutdownCommand: sudo shutdown -h now
system:
  actions:
  - action: restart_redeem
    command: sudo systemctl restart redeem.service
    name: Restart Redeem
  - action: restart_toggle
    command: sudo systemctl restart toggle.service
    name: Restart Toggle
  - action: restart mjpg
    command: sudo systemctl restart mjpg.service
    name: Restart Mjpg
temperature: {}
webcam:
  stream: http://kamikaze.local:8080/?action=stream
  snapshot: http://kamikaze.local:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
controls:
  - name: Stepper current and microstepping
    layout: vertical
    children:
    - name: Set
      layout: vertical
      commands: 
       - M906 X%(current_x)s
       - M909 X%(microstepping_x)s
      input:
      - default: 500
        name: Current X
        parameter: current_x
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping X
        parameter: microstepping_x
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands: 
       - M906 Y%(current_y)s
       - M909 Y%(microstepping_y)s
      input:
      - default: 500
        name: Current Y
        parameter: current_y
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping Y
        parameter: microstepping_y
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands: 
       - M906 Z%(current_z)s
       - M909 Z%(microstepping_z)s
      input:
      - default: 500
        name: Current Z
        parameter: current_z
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping Z
        parameter: microstepping_z
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands: 
       - M906 E%(current_e)s
       - M909 E%(microstepping_e)s
      input:
      - default: 500
        name: Current E
        parameter: current_e
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping E
        parameter: microstepping_e
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands: 
       - M906 H%(current_h)s
       - M909 H%(microstepping_h)s
      input:
      - default: 500
        name: Current H
        parameter: current_h
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping H
        parameter: microstepping_h
        slider:
          max: 7
          min: 0
          step: 1
  - name: Stepper steps pr mm and direction
    layout: vertical
    children:
    - name: Set
      layout: vertical
      commands: 
       - M569 X%(direction_x)s
       - M92  X%(steps_pr_mm_x)s
      input:
      - default: 10
        name: Steps pr mm X
        parameter: steps_pr_mm_x
      - default: 1
        name: Invert X
        parameter: direction_x
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands: 
       - M569 Y%(direction_y)s
       - M92  Y%(steps_pr_mm_y)s
      input:
      - default: 10
        name: Steps pr mm Y
        parameter: steps_pr_mm_y
      - default: 1
        name: Invert Y
        parameter: direction_y
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands: 
       - M569 Z%(direction_z)s
       - M92  Z%(steps_pr_mm_z)s
      input:
      - default: 10
        name: Steps pr mm Z
        parameter: steps_pr_mm_z
      - default: 1
        name: Invert Z
        parameter: direction_z
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands: 
       - M569 E%(direction_e)s
       - M92  E%(steps_pr_mm_e)s
      input:
      - default: 10
        name: Steps pr mm E
        parameter: steps_pr_mm_e
      - default: 1
        name: Invert E
        parameter: direction_e
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands: 
       - M569 H%(direction_h)s
       - M92  H%(steps_pr_mm_h)s
      input:
      - default: 10
        name: Steps pr mm H
        parameter: steps_pr_mm_h
      - default: 1
        name: Invert H
        parameter: direction_h
        slider:
          max: 1
          min: -1
          step: 2
